In [1]:
%pip install -e "./Pitmodule"

Obtaining file:///home/adam/NYPD/nypd-finalassignment/Pitmodule
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas in /home/adam/.local/lib/python3.8/site-packages (from Pitmodule==1.0) (1.4.0)
Requirement already satisfied: numpy in /home/adam/.local/lib/python3.8/site-packages (from Pitmodule==1.0) (1.22.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/adam/.local/lib/python3.8/site-packages (from pandas->Pitmodule==1.0) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/adam/.local/lib/python3.8/site-packages (from pandas->Pitmodule==1.0) (2021.3)
Requirement already satisfied: six>=1.5 in /home/adam/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas->Pitmodule==1.0) (1.15.0)
Installing collected packages: Pitmodule
  Attempting uninstall: Pitmodule
    Found existing installation: Pitmodule 1.0
    Uninstalling Pitmodule-1.0:
      Successfully uninstalled Pitmodule-1.0
  Running setup.py develop for Pitmodule
Successfully installed Pitmodule-1.0
Note: you may need to restart the kernel to use updated packages.

In [12]:
from Pitmodule import *
pit2019 = pitmodule.PitFrame(year=2019)
pit2020 = pitmodule.PitFrame(year=2020)

In [13]:
# testowanie uproszczenia, zgdonosci formatu oraz getPIT
pit2020 == pit2019 == pitmodule.PitFrame(is_path=False)
tmp = pit2020.get_PIT()
tmp.data.keys()

dict_keys(['Gminy', 'Powiaty', 'Wojewodztwa', 'Metropolia', 'Miasta_Gminy', 'Miasta_Powiaty'])

In [14]:
# task1 Compare results
t = pit2020.compare(pit2019)
df = t.data["Miasta_Powiaty"]
df[ df["wojewodztwo"] == "mazowieckie"]

,jst,wojewodztwo,powiat,naleznosci2020,naleznosci2019,Roznica(%)
20,Ostrołęka,mazowieckie,-,14430953,15132261,-0.046345
21,Płock,mazowieckie,-,40963925,43155284,-0.050778
22,Radom,mazowieckie,-,58062919,60575893,-0.041485
23,Siedlce,mazowieckie,-,26017876,26980131,-0.035665
24,m. st. Warszawa,mazowieckie,-,1301271209,1339313472,-0.028404

In [23]:
#task2 compare to population
pit2019.data.items()tr

dict_items([('Gminy',       wk  pk  gk gt           jst         wojewodztwo         powiat klDzial  \
0     02  01  01  1   BOLESŁAWIEC        dolnośląskie  bolesławiecki     756
1     02  01  02  2   BOLESŁAWIEC        dolnośląskie  bolesławiecki     756
2     02  01  03  2      GROMADKA        dolnośląskie  bolesławiecki     756
3     02  01  04  3  NOWOGRODZIEC        dolnośląskie  bolesławiecki     756
4     02  01  05  2    OSIECZNICA        dolnośląskie  bolesławiecki     756
...   ..  ..  .. ..           ...                 ...            ...     ...
2406  32  18  01  3         DOBRA  zachodniopomorskie        łobeski     756
2407  32  18  02  3         ŁOBEZ  zachodniopomorskie        łobeski     756
2408  32  18  03  2   RADOWO MAŁE  zachodniopomorskie        łobeski     756
2409  32  18  04  3         RESKO  zachodniopomorskie        łobeski     756
2410  32  18  05  3     WĘGORZYNO  zachodniopomorskie        łobeski     756

     klRozdzial klParagraf naleznosci dochodyWyk saldoNaleznosciOgolem  \
0         75621       0010   42642404   42635709                  6695
1         75621       0010   14042861   14040656                  2205
2         75621       0010    3550411    3549854                   557
3         75621       0010    9498051    9496560                  1491
4         75621       0010    6055695    6054744                   951
...         ...        ...        ...        ...                   ...
2406      75621       0010    2055913    2055590                   323
2407      75621       0010    9303046    9301585                  1461
2408      75621       0010    1714547    1714278                   269
2409      75621       0010    6719306    6718251                  1055
2410      75621       0010    3798826    3798230                   596

     saldoZaleglosciNetto saldoNadplaty
0                    6695           NaN
1                    2205           NaN
2                     557           NaN
3                    1491           NaN
4                     951           NaN
...                   ...           ...
2406                  323           NaN
2407                 1461           NaN
2408                  269           NaN
2409                 1055           NaN
2410                  596           NaN

[2411 rows x 15 columns]), ('Powiaty',      wk  pk gk gt             jst         wojewodztwo powiat klDzial  \
0    02  01  -  -   bolesławiecki        dolnośląskie      -     756
1    02  02  -  -  dzierżoniowski        dolnośląskie      -     756
2    02  03  -  -       głogowski        dolnośląskie      -     756
3    02  04  -  -        górowski        dolnośląskie      -     756
4    02  05  -  -        jaworski        dolnośląskie      -     756
..   ..  .. .. ..             ...                 ...    ...     ...
309  32  14  -  -     stargardzki  zachodniopomorskie      -     756
310  32  15  -  -    szczecinecki  zachodniopomorskie      -     756
311  32  16  -  -      świdwiński  zachodniopomorskie      -     756
312  32  17  -  -         wałecki  zachodniopomorskie      -     756
313  32  18  -  -         łobeski  zachodniopomorskie      -     756

    klRozdzial klParagraf naleznosci dochodyWyk saldoNaleznosciOgolem  \
0        75622       0010   21984822   21981364                  3458
1        75622       0010   21906718   21903272                  3446
2        75622       0010   30347660   30342887                  4773
3        75622       0010    5784270    5783360                   910
4        75622       0010   10550026   10548367                  1659
..         ...        ...        ...        ...                   ...
309      75622       0010   27896289   27891901                  4388
310      75622       0010   15901267   15898766                  2501
311      75622       0010    8990457    8989043                  1414
312      75622       0010   11274515   11272742                  1773
313      75622       0010    6350164    6349165                   999

    saldoZaleglosciNetto saldoNadplaty
0                   3458           NaN
1                   3446           NaN
2                   4773           NaN
3                    910           NaN
4                   1659           NaN
..                   ...           ...
309                 4388           NaN
310                 2501           NaN
311                 1414           NaN
312                 1773           NaN
313                  999           NaN

[314 rows x 15 columns]), ('Wojewodztwa',     wk pk gk gt                  jst wojewodztwo powiat klDzial klRozdzial  \
0   02  -  -  -         dolnośląskie           -      -     756      75623
1   04  -  -  -   kujawsko-pomorskie           -      -     756      75623
2   06  -  -  -            lubelskie           -      -     756      75623
3   08  -  -  -             lubuskie           -      -     756      75623
4   10  -  -  -              łódzkie           -      -     756      75623
5   12  -  -  -          małopolskie           -      -     756      75623
6   14  -  -  -          mazowieckie           -      -     756      75623
7   16  -  -  -             opolskie           -      -     756      75623
8   18  -  -  -         podkarpackie           -      -     756      75623
9   20  -  -  -            podlaskie           -      -     756      75623
10  22  -  -  -            pomorskie           -      -     756      75623
11  24  -  -  -              śląskie           -      -     756      75623
12  26  -  -  -       świętokrzyskie           -      -     756      75623
13  28  -  -  -  warmińsko-mazurskie           -      -     756      75623
14  30  -  -  -        wielkopolskie           -      -     756      75623
15  32  -  -  -   zachodniopomorskie           -      -     756      75623

   klParagraf naleznosci dochodyWyk saldoNaleznosciOgolem  \
0        0010  146544227  146521177                 23050
1        0010   80127009   80114406                 12603
2        0010   67230474   67219899                 10575
3        0010   40315577   40309236                  6341
4        0010  109411405  109394196                 17209
5        0010  156175738  156151173                 24565
6        0010  390020567  389959220                 61347
7        0010   37170920   37165073                  5847
8        0010   67148082   67137520                 10562
9        0010   41536012   41529479                  6533
10       0010  109963374  109946078                 17296
11       0010  224802573  224767214                 35359
12       0010   41007726   41001276                  6450
13       0010   49267070   49259321                  7749
14       0010  168838005  168811448                 26557
15       0010   69278810   69267913                 10897

   saldoZaleglosciNetto saldoNadplaty
0                 23050           NaN
1                 12603           NaN
2                 10575           NaN
3                  6341           NaN
4                 17209           NaN
5                 24565           NaN
6                 61347           NaN
7                  5847           NaN
8                 10562           NaN
9                  6533           NaN
10                17296           NaN
11                35359           NaN
12                 6450           NaN
13                 7749           NaN
14                26557           NaN
15                10897           NaN  ), ('Metropolia',    wk pk gk gt                                   jst wojewodztwo powiat  \
0  24  -  -  -  Górnośląsko-Zagłębiowska\nMetropolia     śląskie      -

  klDzial klRozdzial klParagraf naleznosci dochodyWyk saldoNaleznosciOgolem  \
0     756      75634       0010  375850188  375789983                 60205

  saldoZaleglosciNetto saldoNadplaty
0                60205           NaN  ), ('Miasta_Gminy',      wk  pk gk gt           jst         wojewodztwo powiat klDzial klRozdzial  \
0    02  61  -  -  Jelenia Góra        dolnośląskie      -     756      75621
2    02  62  -  -       Legnica        dolnośląskie      -     756      75621
4    02  64  -  -       Wrocław        dolnośląskie      -     756      75621
6    02  65  -  -     Wałbrzych        dolnośląskie      -     756      75621
8    04  61  -  -     Bydgoszcz  kujawsko-pomorskie      -     756      75621
..   ..  .. .. ..           ...                 ...    ...     ...        ...
122  30  63  -  -        Leszno       wielkopolskie      -     756      75621
124  30  64  -  -        Poznań       wielkopolskie      -     756      75621
126  32  61  -  -      Koszalin  zachodniopomorskie      -     756      75621
128  32  62  -  -      Szczecin  zachodniopomorskie      -     756      75621
130  32  63  -  -   Świnoujście  zachodniopomorskie      -     756      75621

    klParagraf  naleznosci  dochodyWyk saldoNaleznosciOgolem  \
0         0010    84424413    84411158                 13255
2         0010   112627141   112609457                 17684
4         0010  1161913172  1161730741                182431
6         0010   103099258   103083070                 16188
8         0010   420822849   420756776                 66073
..         ...         ...         ...                   ...
122       0010    87112808    87099130                 13678
124       0010   961853336   961702316                151020
126       0010   132448040   132427244                 20796
128       0010   503933861   503854738                 79123
130       0010    43593627    43586782                  6845

    saldoZaleglosciNetto saldoNadplaty
0                  13255           NaN
2                  17684           NaN
4                 182431           NaN
6                  16188           NaN
8                  66073           NaN
..                   ...           ...
122                13678           NaN
124               151020           NaN
126                20796           NaN
128                79123           NaN
130                 6845           NaN

[66 rows x 15 columns]), ('Miasta_Powiaty',      wk  pk gk gt           jst         wojewodztwo powiat klDzial klRozdzial  \
1    02  61  -  -  Jelenia Góra        dolnośląskie      -     756      75622
3    02  62  -  -       Legnica        dolnośląskie      -     756      75622
5    02  64  -  -       Wrocław        dolnośląskie      -     756      75622
7    02  65  -  -     Wałbrzych        dolnośląskie      -     756      75622
9    04  61  -  -     Bydgoszcz  kujawsko-pomorskie      -     756      75622
..   ..  .. .. ..           ...                 ...    ...     ...        ...
123  30  63  -  -        Leszno       wielkopolskie      -     756      75622
125  30  64  -  -        Poznań       wielkopolskie      -     756      75622
127  32  61  -  -      Koszalin  zachodniopomorskie      -     756      75622
129  32  62  -  -      Szczecin  zachodniopomorskie      -     756      75622
131  32  63  -  -   Świnoujście  zachodniopomorskie      -     756      75622

    klParagraf naleznosci dochodyWyk saldoNaleznosciOgolem  \
1         0010   22724531   22720957                  3574
3         0010   30315863   30311095                  4768
5         0010  312752341  312703148                 49193
7         0010   27751242   27746877                  4365
9         0010  113272948  113255131                 17817
..         ...        ...        ...                   ...
123       0010   23448167   23444479                  3688
125       0010  258902202  258861479                 40723
127       0010   35651058   35645450                  5608
129       0010  135643951  135622616                 21335
131       0010   11734104   11732258                  1846

    saldoZaleglosciNetto saldoNadplaty
1                   3574           NaN
3                   4768           NaN
5                  49193           NaN
7                   4365           NaN
9                  17817           NaN
..                   ...           ...
123                 3688           NaN
125                40723           NaN
127                 5608           NaN
129                21335           NaN
131                 1846           NaN

[66 rows x 15 columns])])

In [6]:
# testowanie ludosc 
# calculate per population
from population import *
populacje2020 = PopulationFrame()
populacje2020.data["Powiaty"]

Index(['Gminy', 'id', 'ludnosc'], dtype='object')
Index(['Powiaty', 'id', 'ludnosc'], dtype='object')

/home/adam/NYPD/nypd-finalassignment/Pitmodule/population.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.drop(frame.iloc[:,3:lastcol],axis=1,inplace=True)
/home/adam/NYPD/nypd-finalassignment/Pitmodule/population.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.drop(["id"],axis =1,inplace=True)
/home/adam/NYPD/nypd-finalassignment/Pitmodule/population.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.drop(frame.iloc[:,3:lastcol],axis=1,inplace=True)
/home/adam/NYPD/nypd-finalassignment/Pitmodule/population.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.drop(["id"],axis =1,inplace=True)
/home/adam/NYPD/nypd-finalassignment/Pitmodule/population.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wojew.drop(wojew.iloc[:,2:wojew.shape[1]],axis=1,inplace=True)
/home/adam/NYPD/nypd-finalassignment/Pitmodule/population.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wojew.drop(wojew.index[17:],axis=0,inplace=True)

                            Powiaty  ludnosc
0           bolesławiecki              89762
1           dzierżoniowski             99935
2           głogowski                  88447
3           górowski                   34552
4           jaworski                   49734
..                              ...      ...
375         świdwiński                 46394
376         wałecki                    52707
377  M.Koszalin                       106235
378  M.Szczecin                       398255
379  M.Świnoujście                     40948

[380 rows x 2 columns]

In [11]:
gminy_populacje = populacje2020.data["Gminy"]
gminy_populacje["Gminy"].strcontain()

                 Gminy  ludnosc
0        M.Bolesławiec    38486
1        G.Bolesławiec    14863
2           G.Gromadka     5317
3     M-W.Nowogrodziec    15229
4       M.Nowogrodziec     4263
...                ...      ...
3756       M.Węgorzyno     2771
3757       G.Węgorzyno     4085
3758        M.Koszalin   106235
3759        M.Szczecin   398255
3760     M.Świnoujście    40948

[3761 rows x 2 columns]

In [8]:
pop_gminy_2020 = populacje2020.data["Powiaty"]
o